// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_AS1PorYK8fjf413n3CRP3PZ_jLU98bs',
    appId: '1:465459614850:web:5b898c83fc4c52a038509b',
    messagingSenderId: '465459614850',
    projectId: 'flutter-chat-app-44b71',
    authDomain: 'flutter-chat-app-44b71.firebaseapp.com',
    storageBucket: 'flutter-chat-app-44b71.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD56aSxDz4kFcwH5nkHzUAX0JzRwczNRMM',
    appId: '1:465459614850:android:f5beb0f6fc73154538509b',
    messagingSenderId: '465459614850',
    projectId: 'flutter-chat-app-44b71',
    storageBucket: 'flutter-chat-app-44b71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQuvYQ25aRYttgA5M6dguwpFSFckcjsN4',
    appId: '1:465459614850:ios:1c3c605640642ef738509b',
    messagingSenderId: '465459614850',
    projectId: 'flutter-chat-app-44b71',
    storageBucket: 'flutter-chat-app-44b71.appspot.com',
    iosBundleId: 'com.example.chatAppTest1411',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQuvYQ25aRYttgA5M6dguwpFSFckcjsN4',
    appId: '1:465459614850:ios:df0905469d2a560d38509b',
    messagingSenderId: '465459614850',
    projectId: 'flutter-chat-app-44b71',
    storageBucket: 'flutter-chat-app-44b71.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
